sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '5'

services:
  - couchdb

before_install:
  - npm i -g npm@^3.0.0

# before_script:
#   - npm prune

script: npm run $COMMAND

env:
  matrix:
  - COMMAND='lint'
  - COMMAND='build'
  - COMMAND='test'

after_success:
  - npm run semantic-release

branches:
  only:
    - "master"
